---
title: "Prediction of Global Food Prices"
author: "Morgan Hager-Perry"
date: "2025-03-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(quantmod)
library(forecast)
library(zoo) 
library(xts)
library(tsibble)
library(fpp3)
```

## Stock Database import and set up

```{r}

#pulling the stock ticker for SP500 Food Products Index - Same time range as other dataset
getSymbols("^SP500-302020",
           src="yahoo",
           from = "2003-01-01",
           to = "2020-12-31")


# Get the closing prices as an xts object
stock_data <- Cl(`SP500-302020`)  

# Create a complete time sequence including weekends
all_dates <- seq.Date(from = as.Date("2003-01-02"), to = as.Date("2020-12-31"), by = "day")
stock_data_full <- merge(stock_data, xts(, all_dates))  # Merge with full date sequence

#adjusting the column names 
colnames(stock_data_full) <- c("Close")

# Check the result
head(stock_data_full)

```

## Fill missing values

```{r}

# Forward fill the missing values
stock_data_filled <- na.locf(stock_data_full)

# View the data after filling missing values
head(stock_data_filled)

```

## plotting the time series

```{r}

plot(stock_data_filled)

```

## Decomposition Plot

```{r}

SP500_ts <- ts(stock_data_filled,frequency=365)
plot(decompose(SP500_ts))

```

## Visualization 1 - Trend

```{r}

SP500_ts.decom <- decompose(SP500_ts, type = "mult")
plot(SP500_ts.decom)
Trend <- SP500_ts.decom$trend
Seasonal <- SP500_ts.decom$seasonal
ts.plot(cbind(Trend, Trend * Seasonal), lty=1:2)

```

## Visualization 2 - ACF Plot

```{r}

acf(SP500_ts)

```

## Visualization 3 - Seasonality

```{r}

# Convert xts to tsibble
df <- data.frame(Date = zoo::index(stock_data_filled), Close = zoo::coredata(stock_data_filled))
tsibble_data <- as_tsibble(df, index = Date)

#plot the seasonality chart
tsibble_data %>%
  gg_season(Close, labels = "both") +
  labs(y = "Closing Price ($)",
       title = "Seasonal plot: S&P500 Food Price Index")

```

## Visualization 4 - Moving Averages

```{r}

#take a subset of the data for readability of chart
tsibble_data_subset <- tail(tsibble_data,100)

#create moving averages
tsibble_data_ma <- tsibble_data_subset |>
  mutate(
    `5-MA` = slider::slide_dbl(Close, mean,
                               .before = 2, .after = 2, .complete = TRUE),
    '7-MA' = slider::slide_dbl(Close, mean,
                               .before = 3, .after = 3, .complete = TRUE)            
    
  )

#plot the data
tsibble_data_ma |>
  autoplot(Close) +
  geom_line(aes(y = `5-MA`), colour = "orange") +
  geom_line(aes(y = `7-MA`), colour = "green") +
  labs(y = "Closing Price ($)",
       x = "Month",
       title = "Closing Price for S&P500 Food Price Index")

```